whatis("NVIDIA HPC-X toolkit")
family("mpi")
extensions("hcoll/4.8.3230, ucx/1.18.0, ucc/1.4.0, 4.1.7rc1, sharp/3.9.0")

local hpcx_home = "/hpc/m3/apps/hpcx/hpcx-v2.21.2-gcc-inbox-ubuntu22.04-cuda12-x86_64"
local mpi_home = pathJoin(hpcx_home, "hpcx-ompi-gcc-13.4.0")

setenv("HPCX_DIR", hpcx_home)
setenv("HPCX_HOME", hpcx_home)
setenv("HPCX_UCX_DIR", pathJoin(hpcx_home, "/ucx/mt"))
setenv("HPCX_SHARP_DIR", pathJoin(hpcx_home, "/sharp"))
setenv("HPCX_HCOLL_DIR", pathJoin(hpcx_home, "/hcoll"))
setenv("HPCX_NCCL_RDMA_SHARP_PLUGIN_DIR", pathJoin(hpcx_home, "/nccl_rdma_sharp_plugin"))
setenv("HPCX_CLUSTERKIT_DIR", pathJoin(hpcx_home, "/clusterkit"))
setenv("HPCX_MPI_DIR", mpi_home)
setenv("HPCX_OSHMEM_DIR", mpi_home)
prepend_path("PATH", pathJoin(hpcx_home, "/ucx/mt/bin"))
prepend_path("PATH", pathJoin(hpcx_home, "/hcoll/bin"))
prepend_path("PATH", pathJoin(hpcx_home, "/sharp/bin"))
prepend_path("PATH", pathJoin(hpcx_home, "/clusterkit/bin"))
prepend_path("LD_LIBRARY_PATH", pathJoin(hpcx_home, "/ucx/mt/lib"))
prepend_path("LD_LIBRARY_PATH", pathJoin(hpcx_home, "/ucx/mt/lib/ucx"))
prepend_path("LD_LIBRARY_PATH", pathJoin(hpcx_home, "/hcoll/lib"))
prepend_path("LD_LIBRARY_PATH", pathJoin(hpcx_home, "/sharp/lib"))
prepend_path("LD_LIBRARY_PATH", pathJoin(hpcx_home, "/nccl_rdma_sharp_plugin/lib"))
prepend_path("LIBRARY_PATH", pathJoin(hpcx_home, "/ucx/mt/lib"))
prepend_path("LIBRARY_PATH", pathJoin(hpcx_home, "/hcoll/lib"))
prepend_path("LIBRARY_PATH", pathJoin(hpcx_home, "/sharp/lib"))
prepend_path("LIBRARY_PATH", pathJoin(hpcx_home, "/nccl_rdma_sharp_plugin/lib"))
prepend_path("CPATH", pathJoin(hpcx_home, "/hcoll/include"))
prepend_path("CPATH", pathJoin(hpcx_home, "/sharp/include"))
prepend_path("CPATH", pathJoin(hpcx_home, "/ucx/mt/include"))
prepend_path("CPATH", pathJoin(mpi_home, "/include"))
prepend_path("PKG_CONFIG_PATH", pathJoin(hpcx_home, "/hcoll/lib/pkgconfig"))
prepend_path("PKG_CONFIG_PATH", pathJoin(hpcx_home, "/sharp/lib/pkgconfig"))
prepend_path("PKG_CONFIG_PATH", pathJoin(hpcx_home, "/ucx/mt/lib/pkgconfig"))
prepend_path("PKG_CONFIG_PATH", pathJoin(hpcx_home, "/ompi/lib/pkgconfig"))
prepend_path("MANPATH", pathJoin(mpi_home, "/share/man"))
setenv("OPAL_PREFIX", mpi_home)
setenv("PMIX_INSTALL_PREFIX", mpi_home)
setenv("OMPI_HOME", mpi_home)
setenv("MPI_HOME", mpi_home)
setenv("OSHMEM_HOME", mpi_home)
setenv("SHMEM_HOME", mpi_home)
prepend_path("PATH", pathJoin(mpi_home, "/bin"))
prepend_path("LD_LIBRARY_PATH", pathJoin(mpi_home, "/lib"))
prepend_path("LIBRARY_PATH", pathJoin(mpi_home, "/lib"))
setenv("SLURM_MPI_TYPE","pmix_v5")
setenv("UCX_NET_DEVICES","mlx5_0:1")
setenv("UCX_TLS","sm,ib,rc_x")
prepend_path("PATH","/hpc/sys/apps/pmix/current/bin")
prepend_path("LD_LIBRARY_PATH","/hpc/sys/apps/pmix/current/lib")
prepend_path("LIBRARY_PATH","/hpc/sys/apps/pmix/current/lib")

help([[Name: HPC-X
Version: 2.21.1
Website: https://developer.nvidia.com/networking/hpc-x

NVIDIA® HPC-X® is a comprehensive software package that includes Message Passing Interface (MPI), Symmetrical Hierarchical Memory (SHMEM) and Partitioned Global Address Space (PGAS) communications libraries, and various acceleration packages. 
]])