whatis("MATLAB R2023a")
family("matlab")
prepend_path("PATH","/hpc/m3/apps/matlab/r2023a/bin")
prepend_path("LD_LIBRARY_PATH","/hpc/m3/apps/matlab/r2023a/bin/glnxa64/")
setenv("MATLABROOT","/hpc/m3/apps/matlab/r2023a")
