whatis("MATLAB R2024a")
family("matlab")
prepend_path("PATH","/hpc/m3/apps/Matlab/r2024a/bin")
prepend_path("LD_LIBRARY_PATH","/hpc/m3/apps/Matlab/r2024a/bin/glnxa64/")
setenv("MATLABROOT","/hpc/m3/apps/Matlab/r2024a")
