title: "SMU HPC Documentation"
author: "Southern Methodist University"
logo: "./images/smu_logo.jpg"
copyright: "2023-2025"
execute:
  execute_notebooks: "off"
html:
  favicon: "./images/favicon.ico"
parse:
  myst_enable_extensions:
    - colon_fence
    - dollarmath
    - linkify
    - substitution
    - tasklist
    - html_image
